### ISSUE TITLE
icons not shown

### ISSUE THREAD

**Issue by bobblkabb** [nwg-piotr/nwg-bar#23] opened 2023-08-15 11:18 UTC
Hello,

Installed nwg-bar 0.1.3 on nixos (via configuration.nix) and even go, gtk-layer-shell and gtk3 but buttons are not shown only boxes.
Running hyprland.

icons shown in bar.json are available, for instance:
"icon": "/nix/store/pfwerf23fw3efr23fe3fefg42t23-nwg-bar-0.1.3/share/nwg-bar/images/system-lock-screen.svg"

**Comment by nwg-piotr** [comment] 2023-08-15 11:25
1. Show me your `bar.json`;
2. Run the bar from the terminal, show me the output.

**Comment by bobblkabb** [comment] 2023-08-15 13:08
[bar.json.txt](https://github.com/nwg-piotr/nwg-bar/files/12343689/bar.json.txt)
[shell-output.txt](https://github.com/nwg-piotr/nwg-bar/files/12343704/shell-output.txt)

**Comment by nwg-piotr** [comment] 2023-08-15 13:15
```text
Couldn’t recognize the image file format for file “/nix/store/pfz809cg2l32iy7kznz0mn47f2f9i19r-nwg-bar-0.1.3/share/nwg-bar/images/system-lock-screen.svg”
Couldn’t recognize the image file format for file “/nix/store/pfz809cg2l32iy7kznz0mn47f2f9i19r-nwg-bar-0.1.3/share/nwg-bar/images/system-log-out.svg”
Couldn’t recognize the image file format for file “/nix/store/pfz809cg2l32iy7kznz0mn47f2f9i19r-nwg-bar-0.1.3/share/nwg-bar/images/system-reboot.svg”
Couldn’t recognize the image file format for file “/nix/store/pfz809cg2l32iy7kznz0mn47f2f9i19r-nwg-bar-0.1.3/share/nwg-bar/images/system-shutdown.svg”
```

Check what's wrong with your .svg images.

**Comment by iFreilicht** [comment] 2023-08-25 08:30
I had a look at this just now, and the images themselves seem to be identical to those in this repository:

```
$ git clone git@github.com:nwg-piotr/nwg-bar.git
$ cd nwg-bar 
$ diff -s images /nix/store/pfz809cg2l32iy7kznz0mn47f2f9i19r-nwg-bar-0.1.3/share/nwg-bar/images
Files images/system-lock-screen.svg and /nix/store/pfz809cg2l32iy7kznz0mn47f2f9i19r-nwg-bar-0.1.3/share/nwg-bar/images/system-lock-screen.svg are identical
Files images/system-log-out.svg and /nix/store/pfz809cg2l32iy7kznz0mn47f2f9i19r-nwg-bar-0.1.3/share/nwg-bar/images/system-log-out.svg are identical
Files images/system-reboot.svg and /nix/store/pfz809cg2l32iy7kznz0mn47f2f9i19r-nwg-bar-0.1.3/share/nwg-bar/images/system-reboot.svg are identical
Files images/system-shutdown.svg and /nix/store/pfz809cg2l32iy7kznz0mn47f2f9i19r-nwg-bar-0.1.3/share/nwg-bar/images/system-shutdown.svg are identical
```

It also seems the string "Couldn't recognize the image file format" doesn't appear in this repository, so this is likely an issue with nwg-bar not being packaged 100% correctly in nixpkgs.

There's an [existing issue regarding this with the `nwg-launchers` package in nixpkgs](https://github.com/NixOS/nixpkgs/issues/152761) that seems to be caused by the same oversight, most likely missing dependencies that are implicitly expected to exist.

**Comment by nwg-piotr** [comment] 2023-08-25 08:32
Those are just images that should have been installed as a part of the package.

**Comment by iFreilicht** [comment] 2023-08-25 08:35
Yes, and they are. The issue is more deeply rooted in [the way GTK handles images, specifically GdkPixbuf](https://nixos.org/manual/nixpkgs/stable/#ssec-gnome-gdk-pixbuf-loaders). There is nothing you can do on your side to fix this, this is purely a problem in NixOS.

**Comment by nwg-piotr** [comment] 2023-08-25 08:37
Closing, if so.

**Closed by nwg-piotr** 2023-08-25 08:37 UTC
